services:
  front_end:
    build:
      context: ./front-end
    volumes:
      - ./front-end:/var/www/html
      - ./front-end/node_modules:/var/www/html/node_modules 
    ports:
      - "8000:9000"
      - "5173:5173"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
      - SERVICE_A_PORT=8001 # Default service-a port can be changed in environment file
    depends_on:
      - service_a
    command: sh -c "npm run dev & php artisan serve --host=0.0.0.0 --port=9000"

  service_a:
    build:
      context: ./service-a
    volumes:
      - ./service-a:/var/www/html
    ports:
      - "${SERVICE_A_PORT:-8001}:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - SERVICE_B_PORT=8002 # Default service-b port can be changed in environment file
    depends_on:
      - rabbitmq
    command: sh -c "php artisan serve --host=0.0.0.0 --port=9000"

  service_b:
    build:
      context: ./service-b
    volumes:
      - ./service-b:/var/www/html
    ports:
      - "${SERVICE_B_PORT:-8002}:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - rabbitmq
    command: sh -c "php artisan serve --host=0.0.0.0 --port=9000"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
