apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
    name: rabbitmq-subscription
spec:
    pubsubname: rabbitmq-pubsub
    topic: "default"
    route: "/api/consume"
scopes:
    - "service_b"
